# Generated by Django 4.2.1 on 2023-05-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_countchicken_quantity_of_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countchicken',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
